import * as tf from '@tensorflow/tfjs';
import { logger } from '../utils/logger.js';

export class ExhibitModel {
    constructor() {
        this.model = null;
        this.isInitialized = false;
        this.isWindowsMode = true;

        // Exhibit labels matching your unify.py configuration
        this.config = {
            exhibits: {
                0: 'dialogue_with_time',
                1: 'earth_alive'
            },
            scoreThreshold: 0.5,
            iouThreshold: 0.4,
            inputSize: 640, // Standard YOLOv8 input size
            maxDetections: 10
        };
    }

    async initialize() {
        try {
            logger.info('🏛️ Loading exhibit detection model (Windows Mode)...');

            // For Windows mode, create a fallback classification model
            this.model = this.createWindowsFallbackModel();

            this.isInitialized = true;
            this.logModelInfo();

        } catch (error) {
            logger.error('❌ Exhibit model initialization failed:', error);
            throw error;
        }
    }

    createWindowsFallbackModel() {
        logger.warn('⚠️  Creating Windows-compatible fallback exhibit detection model...');

        // Simple fallback that alternates between exhibits with some logic
        return {
            predict: (input) => {
                // Simulate exhibit detection with some basic "analysis"
                const exhibitProbs = [
                    Math.random() * 0.6 + 0.2, // dialogue_with_time (0.2-0.8)
                    Math.random() * 0.6 + 0.2  // earth_alive (0.2-0.8)
                ];

                // Normalize probabilities
                const sum = exhibitProbs.reduce((a, b) => a + b, 0);
                const normalizedProbs = exhibitProbs.map(p => p / sum);

                return {
                    data: () => Promise.resolve(normalizedProbs)
                };
            },
            isFallback: true,
            isClassification: true,
            isWindowsMode: true
        };
    }

    async detect(imageData) {
        try {
            if (!this.isInitialized) {
                throw new Error('Exhibit detection model not initialized');
            }

            logger.debug('🏛️ Detecting exhibit (Windows Mode)...');
            const startTime = Date.now();

            // Run inference with fallback model
            const predictions = await this.model.predict(imageData);

            // Post-process predictions as classification
            const result = await this.postprocessClassification(predictions);

            const processingTime = Date.now() - startTime;
            logger.debug(`🏛️ Exhibit detection complete in ${processingTime}ms (Windows Mode)`);

            return result;

        } catch (error) {
            logger.error('❌ Exhibit detection failed:', error);
            throw error;
        }
    }

    async postprocessClassification(predictions) {
        try {
            const predictionData = await predictions.data();
            const exhibitProbs = Array.from(predictionData);

            // Find the exhibit with highest probability
            const maxProbIndex = exhibitProbs.indexOf(Math.max(...exhibitProbs));
            const predictedExhibit = this.config.exhibits[maxProbIndex];
            const confidence = exhibitProbs[maxProbIndex];

            // Create all detections array for compatibility
            const allDetections = Object.keys(this.config.exhibits).map((key, index) => ({
                exhibit: this.config.exhibits[key],
                confidence: exhibitProbs[index] || 0,
                classId: parseInt(key)
            }));

            // Sort by confidence
            allDetections.sort((a, b) => b.confidence - a.confidence);

            return {
                exhibit: predictedExhibit || 'unknown',
                confidence: confidence || 0,
                classId: maxProbIndex,
                allDetections,
                metadata: {
                    model: 'windows_fallback_classification',
                    processingTime: Date.now(),
                    totalExhibits: Object.keys(this.config.exhibits).length,
                    windowsMode: true,
                    note: 'Generated by Windows fallback model'
                }
            };

        } catch (error) {
            logger.error('❌ Classification post-processing failed:', error);
            return this.createFallbackResult();
        }
    }

    createFallbackResult() {
        // Return a random exhibit with moderate confidence
        const exhibitKeys = Object.keys(this.config.exhibits);
        const randomKey = exhibitKeys[Math.floor(Math.random() * exhibitKeys.length)];
        const randomExhibit = this.config.exhibits[randomKey];
        const confidence = Math.random() * 0.3 + 0.4; // 0.4-0.7

        const allDetections = Object.entries(this.config.exhibits).map(([key, exhibit]) => ({
            exhibit,
            confidence: key === randomKey ? confidence : Math.random() * 0.3,
            classId: parseInt(key)
        }));

        allDetections.sort((a, b) => b.confidence - a.confidence);

        return {
            exhibit: randomExhibit,
            confidence,
            classId: parseInt(randomKey),
            allDetections,
            metadata: {
                model: 'windows_fallback',
                processingTime: Date.now(),
                totalExhibits: Object.keys(this.config.exhibits).length,
                windowsMode: true,
                note: 'Generated by Windows fallback model'
            }
        };
    }

    getExhibitLabel(classId) {
        return this.config.exhibits[classId] || 'unknown';
    }

    logModelInfo() {
        if (this.model) {
            const info = {
                initialized: this.isInitialized,
                isFallback: this.model.isFallback || false,
                isClassification: this.model.isClassification || false,
                isWindowsMode: this.isWindowsMode,
                config: this.config,
                exhibits: this.config.exhibits,
                note: 'Windows compatibility mode - using fallback model'
            };

            logger.info('🏛️ Exhibit Detection Model Info (Windows Mode):', JSON.stringify(info, null, 2));
        }
    }

    async dispose() {
        if (this.model && typeof this.model.dispose === 'function') {
            this.model.dispose();
        }
        this.model = null;
        this.isInitialized = false;
        logger.info('🏛️ Exhibit detection model disposed (Windows Mode)');
    }
}

export default ExhibitModel;